global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spotify Bot Application
  - job_name: 'spotify-bot'
    static_configs:
      - targets: ['spotify-bot:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Web Dashboard
  - job_name: 'spotify-dashboard'
    static_configs:
      - targets: ['dashboard:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database (if using PostgreSQL)
  - job_name: 'postgres'
    static_configs:
      - targets: ['database:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
